import {
  agileList,
  blogList,
  bookList,
  courseList,
  generalList,
  gitList,
  glossaryList,
  interactiveLearnList,
  libraryList,
  regexList,
  serviceList,
  statisticsList,
  testList,
  toolList,
  wordpressList,
  youtubeList,
} from "./list";

export const routeList = [
  { path: "/", text: "Home", importList: null },
  { path: "tool", text: "Tool", importList: toolList },
  { path: "general", text: "General", importList: generalList },
  { path: "blog", text: "Blog", importList: blogList },
  { path: "youtube", text: "Youtube", importList: youtubeList },
  { path: "courses", text: "Online Courses", importList: courseList },
  { path: "book", text: "Book", importList: bookList },
  { path: "wordpress", text: "WordPress", importList: wordpressList },
  {
    path: "interactive",
    text: "Interactive learning",
    importList: interactiveLearnList,
  },
  { path: "agile", text: "Agile", importList: agileList },
  { path: "library", text: "Library", importList: libraryList },
  { path: "statistics", text: "Statistics", importList: statisticsList },
  { path: "services", text: "Services", importList: serviceList },
  { path: "regex", text: "Regex", importList: regexList },
  { path: "test", text: "Test", importList: testList },
  { path: "glossary", text: "Glossary", importList: glossaryList },
  { path: "git", text: "Git", importList: gitList },
];
